import fs from "fs/promises";
import path from "path";
import sharp from "sharp";
import { exiftool } from "exiftool-vendored";
import { randomUUID } from "crypto";

/**
 * Applique des changements légers et modifie les métadonnées EXIF.
 * - Renomme, EXIF (Comment/Software/Artist/AllDates), taille/quality,
 * - Légère variation de dimensions (+/-2%), luminosité/contraste,
 * - Grain très léger via calque de bruit,
 * - Recompression qualité variable.
 */
export async function mutateImage(inputFile: string, outDir: string, index: number) {
  // 1) Lire l'image pour connaître largeur/hauteur
  const img = sharp(inputFile, { failOn: "none" });
  const meta = await img.metadata();
  const width = meta.width ?? 1024;
  const height = meta.height ?? 1024;

  // 2) Variations aléatoires très légères
  const scale = clamp(randomFloat(0.985, 1.015), 0.97, 1.03); // ±1.5%
  const newW = Math.max(2, Math.round(width * scale));
  const newH = Math.max(2, Math.round(height * scale));

  // luminosité/contraste très subtil
  const brightness = randomFloat(0.985, 1.015);
  // contraste approximé via 'linear': factor ~ contrast
  const contrast = randomFloat(0.985, 1.015);

  // 3) Calque de bruit très léger (grayscale) et opacity faible
  const noise = await makeNoiseBuffer(newW, newH); // Uint8Array aléatoire
  const noiseImg = sharp(noise, {
    raw: { width: newW, height: newH, channels: 1 },
  }).toColourspace("b-w"); // calque mono

  // 4) Qualité de recompression (change légèrement la taille)
  const quality = Math.max(70, Math.min(95, Math.round(randomFloat(80, 92))));

  // 5) Pipeline sharp
  let pipeline = sharp(inputFile)
    .resize(newW, newH, { fit: "fill" })
    .modulate({ brightness })                // luminosité
    .linear(contrast, 0)                     // contraste
    .composite([{                           // bruit très léger
      input: await noiseImg
        .ensureAlpha()
        .png()
        .toBuffer(),
      blend: "overlay",
      opacity: 0.03, // quasi imperceptible
    }]);

  // Encoder selon format d’origine
  const ext = (meta.format ?? "jpeg").toLowerCase();
  const baseName = `img_dup_${index + 1}_${randomUUID().slice(0, 8)}`;
  const outName =
    ext === "png"
      ? `${baseName}.png`
      : ext === "webp"
      ? `${baseName}.webp`
      : `${baseName}.jpg`;

  const outPath = path.join(outDir, outName);

  if (ext === "png") {
    pipeline = pipeline.png({ compressionLevel: 9 });
  } else if (ext === "webp") {
    pipeline = pipeline.webp({ quality });
  } else {
    pipeline = pipeline.jpeg({
      quality,
      chromaSubsampling: "4:2:0",
      mozjpeg: true,
      trellisQuantisation: true,
      overshootDeringing: true,
    });
  }

  await pipeline.toFile(outPath);

  // 6) Écrire métadonnées EXIF arbitraires (différentes à chaque duplication)
  const now = new Date(Date.now() - Math.floor(Math.random() * 86_400_000)); // -0..24h
  await exiftool.write(outPath, {
    AllDates: formatExifDate(now),
    Artist: "ContentDuplicator",
    Software: "ContentDuplicator",
    Comment: `Generated by ContentDuplicator ${randomUUID().slice(0, 6)}`,
    ImageDescription: "Variant",
    XPComment: "Variant",
  }).catch(() => { /* safe-fail, certains formats n’acceptent pas tout */ });

  return outName; // retourne juste le nom (sérialisable)
}

// ---------- helpers ----------
function randomFloat(min: number, max: number) {
  return Math.random() * (max - min) + min;
}
function clamp(x: number, a: number, b: number) {
  return Math.max(a, Math.min(b, x));
}
async function makeNoiseBuffer(w: number, h: number) {
  const n = w * h;
  const buf = Buffer.allocUnsafe(n);
  // bruit très faible autour de 127 (gris moyen) pour overlay doux
  for (let i = 0; i < n; i++) {
    const v = 110 + (Math.random() * 30); // 110..140
    buf[i] = v & 0xff;
  }
  return buf;
}
function pad(n: number) { return String(n).padStart(2, "0"); }
function formatExifDate(d: Date) {
  return `${d.getFullYear()}:${pad(d.getMonth() + 1)}:${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
}