'use server';

// src/app/dashboard/actions.ts
import fs from 'fs/promises';
import path from 'path';
import { revalidatePath } from 'next/cache';

// === Vidéo (ffmpeg) ===
import ffmpeg from 'fluent-ffmpeg';
import ffmpegStatic from 'ffmpeg-static';

// === Image (sharp + exiftool) ===
import sharp from 'sharp';
import { exiftool } from 'exiftool-vendored';

// Répertoire de sortie web/public/out
export const OUT_DIR = path.join(process.cwd(), 'public', 'out');

// Configure le binaire ffmpeg (important sur Vercel)
if (ffmpegStatic) {
  ffmpeg.setFfmpegPath(ffmpegStatic as unknown as string);
}

async function ensureOutDir() {
  await fs.mkdir(OUT_DIR, { recursive: true });
}

export async function listOutputs(): Promise<string[]> {
  await ensureOutDir();
  const entries = await fs.readdir(OUT_DIR);
  return entries
    .filter((f) => !f.startsWith('.'))
    .map((f) => `/out/${f}`)
    .sort((a, b) => (a < b ? 1 : -1));
}

export async function deleteAll(): Promise<void> {
  await ensureOutDir();
  const entries = await fs.readdir(OUT_DIR);
  await Promise.all(
    entries.map((name) => fs.rm(path.join(OUT_DIR, name), { recursive: true, force: true }))
  );
  revalidatePath('/dashboard');
}

/* =========================
   PIPELINE IMAGE (sharp)
   - Bruit très léger
   - Variation très légère de luminosité/contraste
   - Recompression (qualité ~90)
   - EXIF custom
========================= */
async function processImage(inputPath: string, outputPath: string, index: number) {
  // Variation légère pseudo-aléatoire mais stable sur l’index
  const rng = (seed: number) => {
    // petit PRNG deterministic sur l’index
    let x = Math.sin(seed) * 10000;
    return x - Math.floor(x);
  };
  const r = rng(index + 1); // 0..1
  const brightness = 1 + (r - 0.5) * 0.04; // +/- 2%
  const contrast = 1 + (r - 0.5) * 0.04; // +/- 2%

  // Ajout d’un bruit très léger: on passe par raw → add + clamp → repack
  const img = sharp(inputPath).withMetadata();
  const { width, height } = await img.metadata();

  if (!width || !height) {
    // fallback simple
    await img
      .modulate({ brightness, saturation: 1, hue: 0 })
      // sharp n’a pas "contrast" direct; on l’approche via linear()
      .linear(contrast, 128 * (1 - contrast))
      .jpeg({ quality: 90, mozjpeg: true })
      .toFile(outputPath);
  } else {
    const raw = await img
      .ensureAlpha()
      .raw()
      .toBuffer({ resolveWithObject: true });

    const buf = raw.data;
    // bruit: +/- 3 niveaux max (très léger, imperceptible)
    for (let i = 0; i < buf.length; i += 4) {
      // RGB
      for (let c = 0; c < 3; c++) {
        const n = (Math.random() * 6 - 3) | 0; // -3..+3
        let v = buf[i + c] + n;
        if (v < 0) v = 0;
        if (v > 255) v = 255;
        buf[i + c] = v;
      }
    }

    const cooked = sharp(buf, {
      raw: { width, height, channels: 4 },
    })
      .modulate({ brightness })
      .linear(contrast, 128 * (1 - contrast))
      .jpeg({ quality: 90, mozjpeg: true });

    await cooked.toFile(outputPath);
  }

  // Écrit quelques métadonnées EXIF simples
  try {
    await exiftool.write(outputPath, {
      Comment: `Generated by ContentDuplicator #${index}`,
      Artist: 'ContentDuplicator',
      Software: 'ContentDuplicator',
    });
  } catch {}
}

/* =========================
   PIPELINE VIDEO (ffmpeg)
   - Re-encode H.264 (libx264)
   - CRF 22, preset veryfast
   - maxrate/bufsize pour variabilité
   - Métadonnées container
========================= */
async function processVideo(inputPath: string, outputPath: string, index: number) {
  const metaTitle = `Duplicate_${index}`;
  const metaComment = 'Generated by ContentDuplicator';

  await new Promise<void>((resolve, reject) => {
    let lastStdErr = '';

    ffmpeg(inputPath)
      .outputOptions([
        '-c:v libx264',
        '-preset veryfast',
        '-crf 22',
        '-maxrate 4500k',
        '-bufsize 9000k',
        '-c:a aac',
        '-b:a 192k',
        // IMPORTANT: options de métadonnées en format "key=value"
        `-metadata`,
        `title=${metaTitle}`,
        `-metadata`,
        `comment=${metaComment}`,
        // pour aider certains players
        '-movflags +faststart',
      ])
      .on('stderr', (line) => {
        lastStdErr = line;
      })
      .on('end', () => resolve())
      .on('error', (err) => reject(new Error(`ffmpeg failed: ${err.message}\n${lastStdErr}`)))
      .save(outputPath);
  });
}

/* =========================
   ACTION PRINCIPALE
========================= */
export async function duplicate(formData: FormData): Promise<void> {
  await ensureOutDir();

  const file = formData.get('file') as File | null;
  const count = Number(formData.get('count') ?? 3);

  if (!file) throw new Error('Aucun fichier reçu');
  if (!Number.isFinite(count) || count < 1 || count > 20) {
    throw new Error('Paramètre "count" invalide');
  }

  // On écrit d’abord le fichier uploadé sur disque
  const arrayBuffer = await file.arrayBuffer();
  const tmpIn = path.join(OUT_DIR, `tmp_${Date.now()}_${file.name}`);
  await fs.writeFile(tmpIn, Buffer.from(arrayBuffer));

  const isVideo = /\.(mp4|mov|m4v|avi|mkv|webm)$/i.test(file.name);
  const isImage = /\.(png|jpg|jpeg|webp)$/i.test(file.name);

  for (let i = 1; i <= count; i++) {
    const outName = isVideo
      ? `dup_${i}_${crypto.randomUUID()}.mp4`
      : isImage
      ? `dup_${i}_${crypto.randomUUID()}.jpg`
      : `dup_${i}_${crypto.randomUUID()}.bin`;

    const outPath = path.join(OUT_DIR, outName);

    if (isVideo) {
      await processVideo(tmpIn, outPath, i);
    } else if (isImage) {
      await processImage(tmpIn, outPath, i);
    } else {
      // type inconnu → on copie juste
      await fs.copyFile(tmpIn, outPath);
    }
  }

  // Nettoyage temp & fermeture exiftool
  try { await fs.rm(tmpIn, { force: true }); } catch {}
  try { await exiftool.end(); } catch {}

  // rafraîchit la page
  revalidatePath('/dashboard');
}